### ISSUE TITLE
Add more workload types/resources

### ISSUE THREAD

**Issue by jonathan-mayer** [caas-team/GoKubeDownscaler#20]
## Issue

Currently only deployments are implemented and can be scaled.

### Problem to solve

Add more scalable Workloads

### Further details

An example of what one of the scalable.Workload implementations could look like can be found in the [deployments.go](../blob/main/internal/pkg/scalable/deployments.go)
Do not change the default for resources in main.go
Add an entry in the GetResource map in scalable/scalableResources.go
Some resources might need their own schema. currently the code doesn't support this behavior. implement it if needed.

### Proposal

Add a implementation for scalable.Workload of these types:
- [x] apps statefulsets
- [x] apps daemonsets
- [x] argoproj.io rollouts
- [x] autoscaling horizontalpodautoscalers
- [x] batch cronjobs
- [x] batch jobs
- [x] keda.sh scaledobjects
- [x] zalando.org stacks
- [x] policy poddisruptionbudgets
- [x] monitoring prometheuses

### Who can address the issue

Go Dev

**Comment by jonathan-mayer** [comment]
On HPAs make sure to not set the replicas to >1. I would implement this by checking if downscale replicas is >1 and throwing an error (including in the workload events) that an hpa can't/shouldn't be scaled down to 0

**Comment by jonathan-mayer** [comment]
@samuel-esp implemented most of the resources in #31 / #29. I will implement the 2 resources that are left

**Comment by jonathan-mayer** [comment]
argoproj.io rollouts and zalando stacks are implemented in #55

**Comment by samuel-esp** [comment]
Great! @jonathan-mayer thank you!
